import pandas as pd
data = {
    "text": [
        "eggs and toast", "chicken biryani", "coffee and biscuits",
        "burger and fries", "idli sambar", "pasta with sauce",
        "fruit salad", "dal rice", "chips and coke",
        "pancakes with syrup", "grilled cheese sandwich", "momos",
        "noodles with veggies", "oats with milk", "roti sabzi",
        "vada pav", "upma", "ice cream", "samosa", "sandwich and juice",
        "poha", "aloo paratha", "chai and rusk", "masala dosa",
        "rajma chawal", "butter naan and paneer", "fish curry and rice",
        "lemon rice", "methi thepla", "bread pakora",
        "pav bhaji", "kathi roll", "misal pav", "veg biryani",
        "maggie noodles", "uttapam", "kanda poha", "sev puri",
        "moong dal chilla", "kachori and jalebi",
        "medu vada", "pongal", "rava dosa", "sambar rice",
        "curd rice", "banana chips", "bisi bele bath", "appam with stew",
        "rasam rice", "mangalore buns","pesarattu", "ragi dosa", "keema pav", "aloo puri", "beetroot cutlet",
        "chole bhature", "masala puri", "puliogare", "kharabath", "akhni pulao",
        "malabar parotta with curry", "mushroom masala", "vegetable stew", 
        "palak paneer", "tamarind rice", "sabudana khichdi", "sprouts salad",
        "corn chaat", "paneer tikka", "rajma tikki", "methi paratha", 
        "gobi manchurian", "egg curry", "veg kurma", "kootu curry","moong dal halwa", "kachumber salad", "jeera rice", "avial",
        "daliya porridge", "sabudana vada", "vegetable pulao", 
        "baingan bharta", "kal dosa", "aloo tikki chaat", "sattu paratha",
        "tomato bath", "egg bhurji", "makki di roti and sarson da saag",
        "kofta curry", "lauki chana dal", "khichdi", "patra", 
        "idiyappam with coconut milk", "thayir sadam", "thukpa", 
        "paneer bhurji", "veg fried rice", "dal makhani", "paneer paratha",
        "paneer butter masala", "chicken tikka masala", "malai kofta",
        "dal tadka", "butter chicken", "veg handi", "chicken korma",
        "shahi paneer", "matar paneer", "veg jalfrezi", "chicken 65",
        "tandoori roti and sabzi", "garlic naan and paneer", "rumali roti with kebab",
        "methi malai matar", "dum aloo", "bhindi masala", "egg masala curry",
        "veg kolhapuri", "mushroom do pyaza",
        "veg fried rice", "chicken fried rice", "egg fried rice", "veg hakka noodles",
        "chicken hakka noodles", "schezwan noodles", "spaghetti with marinara sauce",
        "penne arrabbiata", "mac and cheese", "vegetable pasta", "prawn biryani",
        "mutton biryani", "chicken biryani", "veg biryani", "hyderabadi biryani",
        "tandoori chicken biryani", "fried rice with paneer", "vegetable pulao", "pulao",
        "vegetable chowmein", "veg spaghetti", "chicken spaghetti", "garlic bread with pasta",
        "coke", "pepsi", "lemon soda", "orange juice", "apple juice",
        "buttermilk", "lassi", "masala chai", "filter coffee", "sweet lime soda",
        "tea", "green tea", "mint lemonade", "nimbu pani", "mango lassi",
        "thums up", "ginger tea", "milkshake", "coconut water", "fruit punch",
        "sugarcane juice", "milk tea", "chilled coffee", "falooda",
        "badam milk", "rose milk", "watermelon juice",
        "vegetable pizza", "cheese pizza", "pepperoni pizza", "margarita pizza",
        "chicken burger", "veg burger", "cheese burger", "paneer tikka burger",
        "chicken wings", "grilled chicken sandwich", "prawn burger", "fish burger",
        "tomato soup", "sweet corn soup", "vegetable soup", "lentil soup",
        "mushroom soup", "pumpkin soup", "hot and sour soup", "manchow soup",
        "clear soup", "cream of tomato soup", "chicken clear soup", "spicy tomato soup",
        "roti", "chapati", "naan", "garlic naan", "butter naan", "tandoori roti",
        "laccha paratha", "aloo paratha", "methi paratha", "paneer paratha", 
        "gobi paratha", "makki di roti", "khakra", "paratha with curd", "rumali roti",
        "thepla", "bajra roti", "jowar roti", "pudina paratha", "dosa", 
        "masala dosa", "rava dosa",
        
    ],
    "label": [
        "breakfast", "lunch", "snacks",
        "dinner", "breakfast", "dinner",
        "snacks", "lunch", "snacks",
        "breakfast", "snacks", "snacks",
        "dinner", "breakfast", "lunch",
        "snacks", "breakfast", "snacks", "snacks", "snacks",
        "breakfast", "breakfast", "snacks", "breakfast",
        "lunch", "dinner", "dinner",
        "lunch", "breakfast", "snacks",
        "dinner", "dinner", "snacks", "dinner",
        "snacks", "breakfast", "breakfast", "snacks",
        "breakfast", "snacks",
        "snacks", "breakfast", "breakfast", "lunch",
        "lunch", "snacks", "lunch", "breakfast",
        "lunch", "breakfast",
        "breakfast", "breakfast", "snacks", "breakfast", "snacks",
        "lunch", "snacks", "lunch", "breakfast", "lunch",
        "dinner", "dinner", "dinner",
        "dinner", "lunch", "breakfast", "snacks",
        "snacks", "snacks", "breakfast",
        "snacks", "dinner", "dinner", "lunch",
         "snacks", "snacks", "lunch", "lunch",
        "breakfast", "snacks", "lunch",
        "dinner", "breakfast", "snacks", "breakfast",
        "breakfast", "breakfast", "lunch",
        "dinner", "lunch", "dinner", "snacks",
        "breakfast", "lunch", "dinner",
        "breakfast", "lunch", "dinner", "breakfast",
        "dinner", "dinner", "dinner",
        "lunch", "dinner", "dinner", "dinner",
        "dinner", "lunch", "lunch", "snacks",
        "dinner", "dinner", "dinner",
        "lunch", "lunch", "lunch", "dinner",
        "dinner", "lunch","lunch", "lunch", "lunch", "snacks",
        "snacks", "snacks", "dinner", "dinner",
        "dinner", "dinner", "lunch", "lunch", "lunch",
        "lunch", "lunch", "dinner", "lunch", "lunch",
        "snacks", "dinner", "dinner", "dinner",
        "snacks", "snacks", "snacks", "snacks", "snacks",
        "breakfast", "breakfast", "snacks", "breakfast", "snacks",
        "snacks", "snacks", "snacks", "snacks", "breakfast",
        "snacks", "snacks", "snacks", "snacks", "snacks",
        "snacks", "snacks", "snacks", "snacks",
        "snacks", "snacks","dinner", "dinner", "dinner", "dinner",
        "snacks", "snacks", "snacks", "snacks",
        "snacks", "snacks", "snacks", "snacks",
        "lunch", "lunch", "lunch", "lunch",
        "lunch", "lunch", "lunch", "lunch",
        "lunch", "lunch", "lunch", "lunch",
        "lunch", "lunch", "dinner", "dinner", "dinner", "dinner",
        "lunch", "breakfast", "breakfast", "breakfast", 
        "breakfast", "lunch", "snacks", "breakfast", "dinner",
        "breakfast", "lunch", "lunch", "breakfast", "lunch",
        "lunch", "lunch","breakfast",
        "breakfast","breakfast"
    ]
}
df = pd.DataFrame(data)
df.to_csv("food_items.csv", index=False)
print("CSV file has been created successfully!")
print(len(data['text']))
print(len(data['label']))
